//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSNadaptor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<TLM_SERVER_URL>")]
        public string TLMwebServer {
            get {
                return ((string)(this["TLMwebServer"]));
            }
            set {
                this["TLMwebServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<SPACECRAFT_ID>")]
        public string SpacecraftID {
            get {
                return ((string)(this["SpacecraftID"]));
            }
            set {
                this["SpacecraftID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AM_USERNAME>")]
        public string OpenAM_username {
            get {
                return ((string)(this["OpenAM_username"]));
            }
            set {
                this["OpenAM_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AM_PASSWORD>")]
        public string OpenAM_password {
            get {
                return ((string)(this["OpenAM_password"]));
            }
            set {
                this["OpenAM_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAuthentication {
            get {
                return ((bool)(this["UseAuthentication"]));
            }
            set {
                this["UseAuthentication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>DESTINATION_IP_1</string>\r\n  <string>DESTINATION_IP_2</string>\r\n</ArrayOfS" +
            "tring>")]
        public global::System.Collections.Specialized.StringCollection udpDestIP {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["udpDestIP"]));
            }
            set {
                this["udpDestIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>UDP_PORT</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection udpPort {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["udpPort"]));
            }
            set {
                this["udpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://<server>/<rel_address>")]
        public string BaseURI {
            get {
                return ((string)(this["BaseURI"]));
            }
            set {
                this["BaseURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RequestRetries {
            get {
                return ((int)(this["RequestRetries"]));
            }
            set {
                this["RequestRetries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int RequestInterval {
            get {
                return ((int)(this["RequestInterval"]));
            }
            set {
                this["RequestInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int ConnectionInterval {
            get {
                return ((int)(this["ConnectionInterval"]));
            }
            set {
                this["ConnectionInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int RequestTimeout {
            get {
                return ((int)(this["RequestTimeout"]));
            }
            set {
                this["RequestTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int deliveryDelay {
            get {
                return ((int)(this["deliveryDelay"]));
            }
            set {
                this["deliveryDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool calcDelay {
            get {
                return ((bool)(this["calcDelay"]));
            }
            set {
                this["calcDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ByteToDelayRatio {
            get {
                return ((int)(this["ByteToDelayRatio"]));
            }
            set {
                this["ByteToDelayRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<SFDU_SYNC_WORD>")]
        public string SFDUsync {
            get {
                return ((string)(this["SFDUsync"]));
            }
            set {
                this["SFDUsync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyServerUsage {
            get {
                return ((bool)(this["ProxyServerUsage"]));
            }
            set {
                this["ProxyServerUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<PROXY_IP>")]
        public string ProxyServerAddress {
            get {
                return ((string)(this["ProxyServerAddress"]));
            }
            set {
                this["ProxyServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int ProxyServerPort {
            get {
                return ((int)(this["ProxyServerPort"]));
            }
            set {
                this["ProxyServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<OPEN_AM_COOKIE>")]
        public string OpenAM_CookieRetrievalURI {
            get {
                return ((string)(this["OpenAM_CookieRetrievalURI"]));
            }
            set {
                this["OpenAM_CookieRetrievalURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<OPEN_AM_AUTH_URL>")]
        public string OpenAM_AuthenticationURI {
            get {
                return ((string)(this["OpenAM_AuthenticationURI"]));
            }
            set {
                this["OpenAM_AuthenticationURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int LengthAttributeOffset {
            get {
                return ((int)(this["LengthAttributeOffset"]));
            }
            set {
                this["LengthAttributeOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int LengthAttributeSize {
            get {
                return ((int)(this["LengthAttributeSize"]));
            }
            set {
                this["LengthAttributeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>&lt;PVL_BLOCKS_DELIMITERS&gt;</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PVLblocks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PVLblocks"]));
            }
            set {
                this["PVLblocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<STATUS_BLOCK_START>")]
        public string PVLdataStart {
            get {
                return ((string)(this["PVLdataStart"]));
            }
            set {
                this["PVLdataStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NONE")]
        public string DebugLevel {
            get {
                return ((string)(this["DebugLevel"]));
            }
            set {
                this["DebugLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\DSNdebug")]
        public string DebugFile {
            get {
                return ((string)(this["DebugFile"]));
            }
            set {
                this["DebugFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<COOKIE_DOMAIN_NAME>")]
        public string CookieDomainName {
            get {
                return ((string)(this["CookieDomainName"]));
            }
            set {
                this["CookieDomainName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<COOKIE_DEFAULT_NAME>")]
        public string CookieDefaultName {
            get {
                return ((string)(this["CookieDefaultName"]));
            }
            set {
                this["CookieDefaultName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int TokenValidity {
            get {
                return ((int)(this["TokenValidity"]));
            }
            set {
                this["TokenValidity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int RetryInterval {
            get {
                return ((int)(this["RetryInterval"]));
            }
            set {
                this["RetryInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int BufferSize {
            get {
                return ((int)(this["BufferSize"]));
            }
            set {
                this["BufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>&lt;QUERY_SERVER&gt;</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection QueryServers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["QueryServers"]));
            }
            set {
                this["QueryServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReadStreamInterval {
            get {
                return ((int)(this["ReadStreamInterval"]));
            }
            set {
                this["ReadStreamInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<SFTP_SERVER_IP>")]
        public string sftpIP {
            get {
                return ((string)(this["sftpIP"]));
            }
            set {
                this["sftpIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<SFTP_USER>")]
        public string sftpUser {
            get {
                return ((string)(this["sftpUser"]));
            }
            set {
                this["sftpUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<SFTP_DIR>")]
        public string sftpDir {
            get {
                return ((string)(this["sftpDir"]));
            }
            set {
                this["sftpDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<SFTP_KET_FILE>")]
        public string sftpKetFileDir {
            get {
                return ((string)(this["sftpKetFileDir"]));
            }
            set {
                this["sftpKetFileDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<SFTP_FILE_HEADER>")]
        public string sftpFileHeader {
            get {
                return ((string)(this["sftpFileHeader"]));
            }
            set {
                this["sftpFileHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800000")]
        public string sftpListInterval {
            get {
                return ((string)(this["sftpListInterval"]));
            }
            set {
                this["sftpListInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\")]
        public string LogFileDir {
            get {
                return ((string)(this["LogFileDir"]));
            }
            set {
                this["LogFileDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<server>")]
        public string OpenAM_server {
            get {
                return ((string)(this["OpenAM_server"]));
            }
            set {
                this["OpenAM_server"] = value;
            }
        }
    }
}
